name: 😼 Test Build

on:
  push:
    branches:
      - master
      - build
  pull_request:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build
      run: |
        $sha = (git rev-parse --short HEAD)
        yarn install --silent
        $env:SHORT_SHA=$sha; yarn build:ci

    - name: Move artifacts
      id: vars
      shell: pwsh
      run: |
        $sha = (git rev-parse --short HEAD)
        md -Name ./dist/artifacts -Force
        Copy-Item ./dist/*.exe -Destination ./dist/artifacts/
        $file = Get-ChildItem -Path ./dist/artifacts/ -Filter "*.exe" | select-object -first 1
        $newName = "$($file.BaseName).$($sha)$($file.Extension)"
        Rename-Item -Path $file.FullName -NewName $newName
        echo "::set-output name=fileName::$($newName)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.vars.outputs.fileName }}
        path: "./dist/artifacts"
